In [288]:
#Delete this code  when you are done with the notebook



In [289]:

import os

xla_flags = os.environ.get('XLA_FLAGS', '')
xla_flags += ' --xla_gpu_triton_gemm_any=True'
os.environ['XLA_FLAGS'] = xla_flags

import bernstein_coeff_order10_arbitinterval, bernstein_coeff_ordern_arbitinterval
from functools import partial
import numpy as np
import jax.numpy as jnp
import mujoco
import mujoco.mjx as mjx 
import jax
import time

from mjx_planner import cem_planner


In [290]:
np.set_printoptions(precision=2, suppress=True, linewidth=150)


In [291]:
num_dof = 2
num_batch = 5
num_steps = 3
maxiter_projection = 5
maxiter_cem = 1
w_pos = 1
w_rot = 0.5
w_col = 10
num_elite = 0.05
timestep = 0.05
max_joint_pos = np.pi 
max_joint_vel=1.0
max_joint_acc=2.0
max_joint_jerk=4.0

start_time = time.time()
#opt_class = cem_planner(num_dof, num_batch, w_pos=3, num_elite=0.1, maxiter_cem=30)	
opt_class = cem_planner(num_dof=num_dof, num_batch=num_batch, num_steps=num_steps, maxiter_cem=maxiter_cem,
                        w_pos=w_pos, w_rot=w_rot, w_col=w_col, num_elite=num_elite, timestep=timestep,
                        maxiter_projection=maxiter_projection,
                        max_joint_pos = max_joint_pos, max_joint_vel=max_joint_vel, max_joint_acc=max_joint_acc, 
                        max_joint_jerk=max_joint_jerk)


# start_time_comp_cem = time.time()



ngeomm 42
167 / 195 contacts involve considered geoms.

 Default backend: gpu
 Model path: /home/alinjar/manipulator/manipulator_mujoco/sampling_based_planner/ur5e_hande_mjx/scene.xml 
 Timestep: 0.05 
 CEM Iter: 1 
 Projection Iter: 5 
 Number of batches: 5 
 Number of steps per trajectory: 3 
 Time per trajectory: 0.15000000000000002 
 Number of variables: 6 
 Number of Total constraints: 36 
 Number of geomteric IDs for colllision: 10


In [292]:
num_dof = 1


start_time = time.time()
#opt_class = cem_planner(num_dof, num_batch, w_pos=3, num_elite=0.1, maxiter_cem=30)	
opt_class_ = cem_planner(num_dof=num_dof, num_batch=num_batch, num_steps=num_steps, maxiter_cem=maxiter_cem,
                        w_pos=w_pos, w_rot=w_rot, w_col=w_col, num_elite=num_elite, timestep=timestep,
                        maxiter_projection=maxiter_projection,
                        max_joint_pos = max_joint_pos, max_joint_vel=max_joint_vel, max_joint_acc=max_joint_acc, 
                        max_joint_jerk=max_joint_jerk)



ngeomm 42
167 / 195 contacts involve considered geoms.

 Default backend: gpu
 Model path: /home/alinjar/manipulator/manipulator_mujoco/sampling_based_planner/ur5e_hande_mjx/scene.xml 
 Timestep: 0.05 
 CEM Iter: 1 
 Projection Iter: 5 
 Number of batches: 5 
 Number of steps per trajectory: 3 
 Time per trajectory: 0.15000000000000002 
 Number of variables: 3 
 Number of Total constraints: 18 
 Number of geomteric IDs for colllision: 10


In [293]:


print(opt_class.A_v_ineq.shape)
print(opt_class_.A_v_ineq.shape) 

print( "A_v_ineq", opt_class.A_v_ineq)
print("A_v_ineq", opt_class_.A_v_ineq) 

(12, 6)
(6, 3)
A_v_ineq [[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [-1. -0. -0. -0. -0. -0.]
 [-0. -1. -0. -0. -0. -0.]
 [-0. -0. -1. -0. -0. -0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [-0. -0. -0. -1. -0. -0.]
 [-0. -0. -0. -0. -1. -0.]
 [-0. -0. -0. -0. -0. -1.]]
A_v_ineq [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [-1. -0. -0.]
 [-0. -1. -0.]
 [-0. -0. -1.]]


In [294]:
from mjx_planner_batch_dof import cem_planner

num_dof = 2


start_time = time.time()
#opt_class = cem_planner(num_dof, num_batch, w_pos=3, num_elite=0.1, maxiter_cem=30)	
opt_class_batch_dof = cem_planner(num_dof=num_dof, num_batch=num_batch, num_steps=num_steps, maxiter_cem=maxiter_cem,
                        w_pos=w_pos, w_rot=w_rot, w_col=w_col, num_elite=num_elite, timestep=timestep,
                        maxiter_projection=maxiter_projection,
                        max_joint_pos = max_joint_pos, max_joint_vel=max_joint_vel, max_joint_acc=max_joint_acc, 
                        max_joint_jerk=max_joint_jerk)


 Default backend: gpu
 Model path: /home/alinjar/manipulator/manipulator_mujoco/sampling_based_planner/ur5e_hande_mjx/scene.xml 
 Timestep: 0.05 
 CEM Iter: 1 
 Projection Iter: 5 
 Number of batches: 5 
 Number of steps per trajectory: 3 
 Time per trajectory: 0.15000000000000002 
 Number of variables: 6 
 Number of Total constraints: 36 
 Number of geomteric IDs for colllision: 10
167 / 195 contacts involve robot.


In [295]:
print(opt_class.A_control.shape)
print(opt_class_.A_control.shape) 

# print( "A_control", opt_class.A_control)
# print("A_control", opt_class_.A_control) 
print(f"opt_class dof {opt_class.num_dof}")
print(f"opt_class_ dof {opt_class_.num_dof}")

#
x= opt_class.A_control.T@opt_class.A_control
x_ = opt_class_.A_control.T@opt_class_.A_control

print(x)
print(x_)
x_error = x[0:opt_class.num, 0:opt_class.num] - x_
print(x_error)

(36, 6)
(18, 3)
opt_class dof 2
opt_class_ dof 1
[[ 320802. -640800.  320000.       0.       0.       0.]
 [-640800. 1281602. -640800.       0.       0.       0.]
 [ 320000. -640800.  320802.       0.       0.       0.]
 [      0.       0.       0.  320802. -640800.  320000.]
 [      0.       0.       0. -640800. 1281602. -640800.]
 [      0.       0.       0.  320000. -640800.  320802.]]
[[ 320802. -640800.  320000.]
 [-640800. 1281602. -640800.]
 [ 320000. -640800.  320802.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [296]:
print(f"opt_class_batch_dof {opt_class_batch_dof.num_dof}")



opt_class_batch_dof 2


In [297]:
print(opt_class.A_projection.shape)
print(opt_class_.A_projection.shape) 

# print( "A_projection", opt_class.A_projection)
# print("A_projection", opt_class_.A_projection) 
print(f"opt_class dof {opt_class.num_dof}")
print(f"opt_class_ dof {opt_class_.num_dof}")

#
cost= opt_class.A_projection.T@opt_class.A_projection + opt_class.rho_ineq*opt_class.A_control.T@opt_class.A_control
cost_ = opt_class_.A_projection.T@opt_class_.A_projection + opt_class_.rho_ineq*opt_class_.A_control.T@opt_class_.A_control

print(cost)
print(cost_)
cost_error = cost[0:opt_class_.num, 0:opt_class_.num] - cost_
print("cost_error", cost_error)

(6, 6)
(3, 3)
opt_class dof 2
opt_class_ dof 1
[[ 320803. -640800.  320000.       0.       0.       0.]
 [-640800. 1281603. -640800.       0.       0.       0.]
 [ 320000. -640800.  320803.       0.       0.       0.]
 [      0.       0.       0.  320803. -640800.  320000.]
 [      0.       0.       0. -640800. 1281603. -640800.]
 [      0.       0.       0.  320000. -640800.  320803.]]
[[ 320803. -640800.  320000.]
 [-640800. 1281603. -640800.]
 [ 320000. -640800.  320803.]]
cost_error [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [298]:
print(f"opt_class dof {opt_class.num_dof}")
print(f"opt_class_ dof {opt_class_.num_dof}")

A_eq = opt_class.A_eq
A_eq_ = opt_class_.A_eq
print(f"opt_class A_eq {A_eq}")
print(f"opt_class_ A_eq_ {A_eq_}")



opt_class dof 2
opt_class_ dof 1
opt_class A_eq [[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
opt_class_ A_eq_ [[1. 0. 0.]]


In [299]:
# KKT system matrix
cost_mat = np.vstack((
    np.hstack((cost, A_eq.T)),
    np.hstack((A_eq, np.zeros((A_eq.shape[0], A_eq.shape[0]))))
))

cost_mat_ = np.vstack((
    np.hstack((cost_, A_eq_.T)),
    np.hstack((A_eq_, np.zeros((A_eq_.shape[0], A_eq_.shape[0]))))
))


print(cost_mat.shape)
print(cost_mat_.shape)

# print(f"cost_mat{cost_mat}")
#print(f"cost_mat{cost_mat[0:4*opt_class_.num_dof, 0:4*opt_class_.num_dof]}")

print("cost_mat:\n", cost_mat)
print("\ncost_mat_:\n", cost_mat_)


(8, 8)
(4, 4)
cost_mat:
 [[ 320803. -640800.  320000.       0.       0.       0.       1.       0.]
 [-640800. 1281603. -640800.       0.       0.       0.       0.       0.]
 [ 320000. -640800.  320803.       0.       0.       0.       0.       0.]
 [      0.       0.       0.  320803. -640800.  320000.       0.       1.]
 [      0.       0.       0. -640800. 1281603. -640800.       0.       0.]
 [      0.       0.       0.  320000. -640800.  320803.       0.       0.]
 [      1.       0.       0.       0.       0.       0.       0.       0.]
 [      0.       0.       0.       1.       0.       0.       0.       0.]]

cost_mat_:
 [[ 320803. -640800.  320000.       1.]
 [-640800. 1281603. -640800.       0.]
 [ 320000. -640800.  320803.       0.]
 [      1.       0.       0.       0.]]


In [300]:

cost_mat_error = cost_mat[0:4*opt_class_.num_dof, 0:4*opt_class_.num_dof] - cost_mat_
print("cost_mat_error", cost_mat_error)


cost_mat_error [[     0.      0.      0.     -1.]
 [     0.      0.      0.      0.]
 [     0.      0.      0.      0.]
 [    -1.      0.      0. 320803.]]


In [301]:
xi_mean = jnp.zeros(opt_class.nvar)
xi_cov = 10.0*jnp.identity(opt_class.nvar)
xi_samples, key = opt_class.compute_xi_samples(opt_class.key, xi_mean, xi_cov)

s_init = jnp.zeros((opt_class.num_batch, opt_class.num_total_constraints))
lamda_init = jnp.zeros((opt_class.num_batch, opt_class.nvar))



xi_mean_ = jnp.zeros(opt_class_.nvar)
xi_cov_ = 10.0*jnp.identity(opt_class_.nvar)
xi_samples_, key = opt_class_.compute_xi_samples(opt_class_.key, xi_mean_, xi_cov_)


s_init_ = jnp.zeros((opt_class_.num_batch, opt_class_.num_total_constraints))
lamda_init_ = jnp.zeros((opt_class_.num_batch, opt_class_.nvar))


s_init_batch = jnp.zeros((opt_class_batch_dof.num_batch, opt_class_batch_dof.num_total_constraints))
lamda_init_batch = jnp.zeros((opt_class_batch_dof.num_batch, opt_class_batch_dof.nvar))

In [302]:
xi_samples = np.tile(xi_samples_, (1, opt_class.num_dof))
xi_samples_batch = xi_samples

In [303]:

print("xi_samples_", xi_samples_)
print("xi_samples", xi_samples)

xi_samples_ [[ 0.24 -1.54  4.08]
 [ 1.64  0.95  0.98]
 [ 1.82 -2.55 -6.29]
 [ 2.02  0.69  0.01]
 [ 5.26  0.64 -0.07]]
xi_samples [[ 0.24 -1.54  4.08  0.24 -1.54  4.08]
 [ 1.64  0.95  0.98  1.64  0.95  0.98]
 [ 1.82 -2.55 -6.29  1.82 -2.55 -6.29]
 [ 2.02  0.69  0.01  2.02  0.69  0.01]
 [ 5.26  0.64 -0.07  5.26  0.64 -0.07]]


In [304]:
init_pos = jnp.array([0.0]*opt_class.num_dof)
init_vel = jnp.array([0.0]*opt_class.num_dof)
thetadot_init = jnp.tile(init_vel, (opt_class.num_batch, 1))
state_term = thetadot_init
b_eq_term = opt_class.compute_boundary_vec_batch(state_term)
xi_projected, _, _, _ = opt_class.compute_feasible_control(lamda_init, s_init, b_eq_term, xi_samples, init_pos)

In [305]:
init_pos_ = jnp.array([0.0]*opt_class_.num_dof)
init_vel_ = jnp.array([0.0]*opt_class_.num_dof)
thetadot_init_ = jnp.tile(init_vel_, (opt_class_.num_batch, 1))
state_term_ = thetadot_init_
b_eq_term_ = opt_class_.compute_boundary_vec_batch(state_term_)
xi_projected_, _, _, _ = opt_class_.compute_feasible_control(lamda_init_, s_init_, b_eq_term_, xi_samples_, init_pos_)

In [306]:
print(lamda_init)
print(lamda_init_)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [307]:

lamda_init_single_dof = lamda_init_
s_init_single_dof = s_init_
b_eq_term_single_dof = b_eq_term_
xi_samples_single_dof = xi_samples_
init_pos_single_dof = init_pos_

# init_pos_batch = jnp.array([0.0]*opt_class_batch_dof.num_dof)
# init_vel_batch = jnp.array([0.0]*opt_class_batch_dof.num_dof)

# thetadot_init_batch = jnp.tile(init_vel_batch, (opt_class_batch_dof.num_batch, 1))
# state_term_batch = thetadot_init_batch
# b_eq_term_batch = opt_class_batch_dof.compute_boundary_vec_batch(state_term_batch)
#xi_projected_batch, _, _, _ = opt_class_batch_dof.compute_feasible_control_single_dof(lamda_init_batch, s_init_batch, b_eq_term_batch, xi_samples_batch, init_pos_batch)
xi_projected_batch, _, _, _ = opt_class_batch_dof.compute_feasible_control_single_dof(lamda_init_single_dof, s_init_single_dof, 
										 b_eq_term_single_dof, xi_samples_single_dof, 
										 init_pos_single_dof)

In [308]:
xi_projected_error = xi_projected_ - xi_projected_batch

In [309]:
xi_samples_reshaped = xi_samples.reshape(opt_class_batch_dof.num_batch, opt_class_batch_dof.num_dof, opt_class_batch_dof.num)
xi_samples_batched_over_dof = jnp.transpose(xi_samples_reshaped, (1, 0, 2)) # shape: (DoF, B, num)

state_term_reshaped = state_term.reshape(opt_class_batch_dof.num_batch, opt_class_batch_dof.num_dof, 1)
state_term_batched_over_dof = jnp.transpose(state_term_reshaped, (1, 0, 2)) #Shape: (DoF, B, 1)

lamda_init_reshaped = lamda_init.reshape(opt_class_batch_dof.num_batch, opt_class_batch_dof.num_dof, opt_class_batch_dof.num)
lamda_init_batched_over_dof = jnp.transpose(lamda_init_reshaped, (1, 0, 2)) # shape: (DoF, B, num)

s_init_reshaped = s_init.reshape(opt_class_batch_dof.num_batch, opt_class_batch_dof.num_dof, opt_class_batch_dof.num_total_constraints_per_dof )
s_init_batched_over_dof = jnp.transpose(s_init_reshaped, (1, 0, 2)) # shape: (DoF, B, num_total_constraints_per_dof)



# #PAss all arguments as positional arguments; not keyword arguments
xi_filtered, primal_residuals, fixed_point_residuals = opt_class_batch_dof.compute_projection_batched_over_dof(
                                                            xi_samples_batched_over_dof, 
                                                            state_term_batched_over_dof, 
                                                            lamda_init_batched_over_dof, 
                                                            s_init_batched_over_dof, 
                                                            init_pos)

#xi_projected_batch_multidof = xi_filtered.reshape(opt_class_batch_dof.num_batch, opt_class_batch_dof.num* opt_class_batch_dof.num_dof)
xi_projected_batch_multidof = xi_filtered.transpose(1, 0, 2).reshape(opt_class_batch_dof.num_batch, -1)
print(xi_projected_batch_multidof.shape)

(5, 6)


In [310]:
print("xi_samples", xi_samples)
print("xi_samples_reshaped", xi_samples_reshaped)


xi_samples [[ 0.24 -1.54  4.08  0.24 -1.54  4.08]
 [ 1.64  0.95  0.98  1.64  0.95  0.98]
 [ 1.82 -2.55 -6.29  1.82 -2.55 -6.29]
 [ 2.02  0.69  0.01  2.02  0.69  0.01]
 [ 5.26  0.64 -0.07  5.26  0.64 -0.07]]
xi_samples_reshaped [[[ 0.24 -1.54  4.08]
  [ 0.24 -1.54  4.08]]

 [[ 1.64  0.95  0.98]
  [ 1.64  0.95  0.98]]

 [[ 1.82 -2.55 -6.29]
  [ 1.82 -2.55 -6.29]]

 [[ 2.02  0.69  0.01]
  [ 2.02  0.69  0.01]]

 [[ 5.26  0.64 -0.07]
  [ 5.26  0.64 -0.07]]]


In [311]:

print("state_term", state_term)
print("state_term_reshaped", state_term_reshaped)

state_term [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
state_term_reshaped [[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]]


In [312]:
print("lamda_init", lamda_init)
print("lamda_init_reshaped", lamda_init_reshaped)

lamda_init [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
lamda_init_reshaped [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [313]:
print(("xi_projected", xi_projected.shape))
print(("xi_projected_", xi_projected_.shape))

print("xi_projected:\n", xi_projected)
print("\nxi_projected_:\n", xi_projected_)
print("\nxi_projected_batch:\n", xi_projected_batch)


('xi_projected', (5, 6))
('xi_projected_', (5, 3))
xi_projected:
 [[-0.    0.    0.01 -0.    0.    0.01]
 [ 0.    0.    0.    0.    0.    0.  ]
 [-0.   -0.01 -0.02 -0.   -0.01 -0.02]
 [-0.    0.    0.   -0.    0.    0.  ]
 [-0.    0.    0.   -0.    0.    0.  ]]

xi_projected_:
 [[-0.    0.    0.01]
 [ 0.    0.    0.  ]
 [-0.   -0.01 -0.02]
 [-0.    0.    0.  ]
 [-0.    0.    0.  ]]

xi_projected_batch:
 [[-0.    0.    0.01]
 [ 0.    0.    0.  ]
 [-0.   -0.01 -0.02]
 [-0.    0.    0.  ]
 [-0.    0.    0.  ]]


In [ ]:
# print("\nxi_filtered:\n", xi_filtered)
print("\nxi_filtered:\n", xi_filtered)
print("\nxi_projected_batch_multidof:\n", xi_projected_batch_multidof)



xi_filtered:
 [[[ 0.    0.02  0.04]
  [ 0.    0.01  0.02]
  [-0.   -0.05 -0.09]
  [ 0.    0.    0.  ]
  [ 0.    0.    0.  ]]

 [[ 0.    0.02  0.04]
  [ 0.    0.01  0.02]
  [-0.   -0.05 -0.09]
  [ 0.    0.    0.  ]
  [ 0.    0.    0.  ]]]

xi_filtered:
 [[[ 0.    0.02  0.04]
  [ 0.    0.01  0.02]
  [-0.   -0.05 -0.09]
  [ 0.    0.    0.  ]
  [ 0.    0.    0.  ]]

 [[ 0.    0.02  0.04]
  [ 0.    0.01  0.02]
  [-0.   -0.05 -0.09]
  [ 0.    0.    0.  ]
  [ 0.    0.    0.  ]]]

xi_projected:
 [[-0.    0.    0.01 -0.    0.    0.01]
 [ 0.    0.    0.    0.    0.    0.  ]
 [-0.   -0.01 -0.02 -0.   -0.01 -0.02]
 [-0.    0.    0.   -0.    0.    0.  ]
 [-0.    0.    0.   -0.    0.    0.  ]]


In [ ]:
print("\nxi_projected_error:\n", xi_projected_error)



In [ ]:
#init_pos = jnp.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
init_pos = jnp.array([1.5, -1.8, 1.75, -1.25, -1.6, 0])
# init_pos = jnp.array([1.0, 1.0, 1.0, 1.0, 1.0, 1.0])
init_vel = jnp.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
init_acc = jnp.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
target_pos = jnp.array([0.0, 0.0, 0.0])
target_rot = jnp.array([0.0, 0.0, 0.0, 1.0])
s_init = jnp.zeros((opt_class.num_batch, opt_class.num_total_constraints))
lamda_init = jnp.zeros((opt_class.num_batch, opt_class.nvar))

cost, best_cost_g, best_cost_r, best_cost_c, best_vels, best_traj, \
xi_mean, xi_cov, thd_all, th_all, avg_primal_res, avg_fixed_res, \
primal_res, fixed_res, _ = opt_class.compute_cem(
    xi_mean,
    xi_cov,
    init_pos,
    init_vel,
    init_acc,
    target_pos,
    target_rot,
    lamda_init,
    s_init,
    xi_samples
)

print(f"best_vels: {best_vels.shape}")
print(f"Total time: {round(time.time()-start_time, 2)}s")
print(f"Compute CEM time: {round(time.time()-start_time_comp_cem, 2)}s")
    

In [ ]:
print(opt_class.Pint.shape)
print(opt_class.P.shape)

# print(opt_class.Pint)
# print(opt_class.P)
# print(opt_class.Pdot)

# initi = np.vstack((opt_class.Pint[0], opt_class.P[0], opt_class.Pdot[0], opt_class.P[-1], opt_class.Pdot[-1]  ))

# print(initi.shape)
# print(initi)

In [ ]:
print(best_vels.shape)
import matplotlib.pyplot as plt
%matplotlib inline
plt.figure()
plt.plot(best_vels)
plt.show()



In [ ]:
print(thd_all.shape)
%matplotlib inline
plt.figure()
plt.plot(thd_all[-1].T)
plt.show()


In [ ]:
vel_start = np.zeros((num_batch, 1))
vel_end = np.zeros((num_batch, 1))

for i in range(num_batch):
    vel_start[i] = thd_all[-1][i][0]
    vel_end[i] = thd_all[-1][i][-1]

print(vel_start.shape)
print(vel_end.shape)

%matplotlib inline

plt.figure()
plt.plot(vel_start)
plt.show()

plt.figure()
plt.plot(vel_end)
plt.show()




In [ ]:
print(th_all.shape)
%matplotlib inline
plt.figure()
plt.plot(th_all[-1].T)
plt.show()

In [ ]:
theta_start = np.zeros((num_batch, 1))
theta_end = np.zeros((num_batch, 1))

for i in range(num_batch):
    theta_start[i] = th_all[-1][i][0]
    theta_end[i] = th_all[-1][i][-1]

print(theta_start.shape)
print(theta_end.shape)

%matplotlib inline
plt.figure()
plt.plot(theta_end)
plt.show()

plt.figure()
plt.plot(theta_start)
plt.show()

In [ ]:
print(primal_res.shape)
print(fixed_res.shape)

print(avg_primal_res.shape)
print(avg_fixed_res.shape)

In [ ]:
%matplotlib inline
plt.figure()
plt.plot(primal_res[-1])
plt.show()

In [ ]:
%matplotlib inline
plt.figure()
plt.plot(fixed_res[-1])
plt.show()